version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: deploy/stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: deploy/validate_service.sh
      timeout: 300
