name: GitHub Actions Demo
on: 
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Need build & test step"
